language: node_js

node_js: 
  - 12

branches: #브랜치
  only:
    - master
env: 
  BUILDROOT="/home/travis/build/spectre3130/gleLog"

cache:
    directories:
     - /usr/lib/node_modules
     - $BUILDROOT/backend/node_modules
     - $BUILDROOT/frontend/node_modules 

install:
  - npm install -g @angular/cli
  - cd $BUILDROOT/backend
  - npm install
  - cd $BUILDROOT/frontend
  - npm install

script: 
  - cd $BUILDROOT/frontend
  - ng build --prod

after_success:
  - cd $BUILDROOT
  - mkdir -p build/backend
  - mkdir -p build/frontend
  - mv $BUILDROOT/backend/* build/backend
  - mv $BUILDROOT/frontend/dist/glelog/* build/frontend
  - mv $BUILDROOT/appspec.yml build
  - cd build
  - zip -r glelog *
  - mkdir -p deploy
  - mv glelog.zip deploy/glelog.zip

deploy: 
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: glelog
    region: ap-northeast-2
    skip_cleanup: true
    acl: public_read
    wait-until-deployed: true
    local_dir: deploy
    upload_dir: build
    on:
      repo: spectre3130/gleLog
      branch: master
      
  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: glelog
    key: build/glelog.zip
    bundle_type: zip
    application: glelog-deploy
    deployment_group: glelog-deploy-group
    region: ap-northeast-2
    wait-until-deployed: true
    on:
      repo: spectre3130/gleLog
      branch: master