language: node_js

node_js: 
  - 12

branches: #브랜치
  only:
    - master
env: 
  BUILDROOT="/home/travis/build/spectre3130/travis_ci_test"

cache:
    directories:
     - /usr/lib/node_modules
     - $BUILDROOT/backend/node_modules
     - $BUILDROOT/frontend/node_modules 

install:
  - npm install -g @angular/cli
  - cd $BUILDROOT/backend
  - npm install
  - cd $BUILDROOT/frontend
  - npm install

script: 
  - cd $BUILDROOT/frontend
  - ng build --prod

after_success:
  - cd $BUILDROOT
  - mkdir -p build/backend
  - mkdir -p build/frontend
  - mv $BUILDROOT/backend/* build/backend
  - mv $BUILDROOT/frontend/dist/frontend/* build/frontend
  - mv $BUILDROOT/appspec.yml build
  - cd build
  - zip -r glelog *
  - mkdir -p deploy
  - mv glelog.zip deploy/glelog.zip

deploy: 
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY # Travis repo settings에 설정된 값
    secret_access_key: $AWS_SECRET_KEY # Travis repo settings에 설정된 값
    bucket: glelog # S3 버킷
    region: ap-northeast-2 #리전
    skip_cleanup: true #클린업 건너뛰기
    acl: public_read #s3 파일권한 ?
    wait-until-deployed: true
    local_dir: deploy
    upload_dir: build
    on:
      repo: spectre3130/travis_ci_test #Github 주소
      branch: master
      
  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY # Travis repo settings에 설정된 값
    secret_access_key: $AWS_SECRET_KEY # Travis repo settings에 설정된 값
    bucket: glelog # S3 버킷
    key: build/glelog.zip # S3 버킷에 저장된 springboot-webservice.zip 파일을 EC2로 배포
    bundle_type: zip
    application: glelog-deploy # 웹 콘솔에서 등록한 CodeDeploy 어플리케이션
    deployment_group: glelog-deploy-group # 웹 콘솔에서 등록한 CodeDeploy 배포 그룹
    region: ap-northeast-2
    wait-until-deployed: true
    on:
      repo: spectre3130/travis_ci_test
      branch: master