version: 0.0
os: linux
files:
  - source:  /
    destination: /home/ubuntu/application/glelog
permissions:
  - object: /home/ubuntu/application
    owner: ubuntu
    group: ubuntu
    mode: 775
hooks:
  AfterInstall: 
    - location: run-deploy.sh
      timeout: 60
